### ISSUE TITLE
Shake.jpg - lowercase issue

### ISSUE THREAD

**Issue by ms-tech-geek** [ibigrock-karan/Bootstrap#46]
rename it to lowercase

**Comment by mekaransethi** [comment]
resolved

**Comment by ms-tech-geek** [comment]
still not solved 
![image](https://user-images.githubusercontent.com/27997683/28191328-2eb4ddaa-684d-11e7-9f47-5ae07b5f6633.png)
