### ISSUE TITLE
Shake.jpg

### ISSUE THREAD

**Issue by ms-tech-geek** [ibigrock-karan/Bootstrap#47]
rename it to lowercase

**Comment by mekaransethi** [comment]
resolved

**Comment by ms-tech-geek** [comment]
still not solved 

![image](https://user-images.githubusercontent.com/27997683/28191312-1e458690-684d-11e7-8577-fb1d66fd06e2.png)
